import type { Medication, Prescription } from '@/domain/prescription';
import { formatFrequency } from './formatFrequency';
import { formatVisitDate } from './groupByVisitDate';

/** One page, already read into a data URI the print renderer can embed. */
export type EmbeddedPage = {
  pageNumber: number;
  dataUri: string;
};

/**
 * Builds the printable HTML for one visit.
 *
 * Pure and synchronous: the caller reads the images, this assembles the
 * document. That split keeps the layout testable without a filesystem, and
 * keeps the file-reading concerns out of the markup.
 */
export function buildVisitHtml(
  prescription: Prescription,
  patientName: string,
  medications: Medication[],
  pages: EmbeddedPage[],
): string {
  return `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      /* No external fonts or stylesheets: the renderer may have no network,
         and this document has to build in airplane mode. */
      * { box-sizing: border-box; }
      body {
        font-family: -apple-system, "Roboto", "Helvetica Neue", sans-serif;
        color: #1A1A18;
        margin: 0;
        padding: 32px;
        font-size: 13px;
        line-height: 1.5;
      }
      h1 { font-size: 20px; margin: 0 0 2px; }
      .date {
        font-size: 11px;
        letter-spacing: 0.6px;
        text-transform: uppercase;
        color: #6B6B66;
        margin-bottom: 10px;
      }
      .patient { font-size: 13px; color: #6B6B66; margin-bottom: 20px; }
      h2 {
        font-size: 11px;
        letter-spacing: 0.6px;
        text-transform: uppercase;
        color: #6B6B66;
        margin: 24px 0 8px;
        border-bottom: 1px solid #E2E2DD;
        padding-bottom: 4px;
      }
      .field { margin-bottom: 8px; }
      .label {
        font-size: 10px;
        letter-spacing: 0.5px;
        text-transform: uppercase;
        color: #6B6B66;
      }
      .medicine { padding: 8px 0; border-bottom: 1px solid #E2E2DD; }
      .medicine-name { font-weight: 600; }
      .medicine-detail { color: #6B6B66; font-size: 12px; }
      .muted { color: #6B6B66; }
      /* Each scan starts a new sheet so a page is never split across two. */
      .page { page-break-before: always; text-align: center; }
      .page img { max-width: 100%; max-height: 900px; }
      .page-label { font-size: 10px; color: #6B6B66; margin-bottom: 6px; }
      .disclaimer {
        margin-top: 28px;
        padding-top: 10px;
        border-top: 1px solid #E2E2DD;
        font-size: 10px;
        color: #6B6B66;
        text-align: center;
      }
    </style>
  </head>
  <body>
    <div class="date">${escapeHtml(formatVisitDate(prescription.visitDate))}</div>
    <h1>${escapeHtml(prescription.doctorName ?? 'Unnamed visit')}</h1>
    <div class="patient">Records for ${escapeHtml(patientName)}</div>

    ${optionalField('Clinic', prescription.clinicName)}
    ${optionalField('Specialty', prescription.specialty)}
    ${optionalField('Reason for visit', prescription.reason)}
    ${optionalField('Notes', prescription.notes)}

    <h2>Medicines</h2>
    ${
      medications.length === 0
        ? '<p class="muted">No medicines recorded for this visit.</p>'
        : medications.map(medicineHtml).join('')
    }

    <div class="disclaimer">
      A copy of a recorded prescription, produced by Prescription Vault.
      Not a medical document and not medical advice.
    </div>

    ${pages.map(pageHtml).join('')}
  </body>
</html>`;
}

function optionalField(label: string, value: string | null): string {
  if (!value) return '';
  return `<div class="field">
      <div class="label">${escapeHtml(label)}</div>
      <div>${escapeHtml(value)}</div>
    </div>`;
}

function medicineHtml(medication: Medication): string {
  const { name, strength, form, frequencyCode, foodRelation, durationDays } = medication;

  const title = [name, strength, form ? `(${form})` : null].filter(Boolean).join(' ');

  // formatFrequency restates the doctor's notation; it never interprets it.
  const detail = [
    formatFrequency(frequencyCode),
    foodRelation,
    durationDays ? `${String(durationDays)} days` : null,
  ]
    .filter(Boolean)
    .join(' · ');

  return `<div class="medicine">
      <div class="medicine-name">${escapeHtml(title)}</div>
      ${detail ? `<div class="medicine-detail">${escapeHtml(detail)}</div>` : ''}
    </div>`;
}

function pageHtml(page: EmbeddedPage): string {
  // The data URI is generated by the app from its own stored files, so it is
  // not escaped — escaping would corrupt the base64 payload.
  return `<div class="page">
      <div class="page-label">Page ${String(page.pageNumber)}</div>
      <img src="${page.dataUri}" />
    </div>`;
}

/**
 * Escapes text before it is interpolated into markup.
 *
 * Every value here came from the user's own keyboard, so this is not a
 * defence against an attacker. It is a correctness fix: a doctor named
 * "O'Brien & Sons" or a note containing "<" would otherwise produce broken
 * markup, and the failure would be a silently mangled document rather than an
 * error.
 */
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}