"""add thumbnail_key to attachments

Revision ID: 1b6bdfaf3c16
Revises: f7eda61e1181
Create Date: 2026-09-06 16:42:24.369713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6bdfaf3c16'
down_revision: Union[str, None] = 'f7eda61e1181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_key', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_key')

    # ### end Alembic commands ###
